import bcrypt from 'bcryptjs'


const data = {
    users: [
        {
            name: 'Basir',
            email: 'admin@example.com',
            password: bcrypt.hashSync('123456'),
            isAdmin: true,
        },
        {
            name: 'John',
            email: 'user@example.com',
            password: bcrypt.hashSync('1234'),
            isAdmin: false,
        },
    ],
    products: [
        {
            // _id: "1",
            name: "Nurofen",
            precio: 600,
            slug: 'nurofen',
            category: "dolor_de_cabeza",
            image: "https://res.cloudinary.com/dbovldjfc/image/upload/v1668718245/farmacia/nurofen_rqqymb.jpg",
            description: "es un medicamento cuyo principio activo es el ibuprofeno, por eso actúa efectivamente aliviando el dolor leve a moderado",
            stock: 10,
            receta: false,
            day: true,
            isFavorite: false,
        },
        {
            // _id: "2",
            name: "Mesalazina",
            precio: 600,
            slug: 'mesalazina',
            category: "dolor_de_panza",
            image: "https://res.cloudinary.com/dbovldjfc/image/upload/v1668718247/farmacia/mesalazina_ubf29a.jpg",
            description: "La mesalamina se usa para tratar la colitis ulcerosa (una afección que provoca hinchazón y llagas en el revestimiento del colon [intestino grueso] y el recto) y también para mantener la mejora de los síntomas de la colitis ulcerosa",
            stock: 15,
            receta: true,
            day: false,
            isFavorite: false,
        },
        {
            name: 'Aspirina',
            precio: 4.41,
            slug: 'aspirina-248',
            category: 'dolor_de_cabeza',
            image: "https://res.cloudinary.com/dbovldjfc/image/upload/v1668718247/farmacia/farmacologia-farmacologia_clinica-medicamentos_313481328_81018046_1706x960_hrgwmc.jpg",
            description: 'una nueva pastilla para tomar, cada ciertas horas',
            stock: 15,
            receta: true,
            day: true,
            isFavorite: false,

        },
        {
            name: 'Al dia siguiente',
            precio: 10,
            slug: 'pastilla-225',
            category: 'dolor_de_cabeza',
            image: "https://res.cloudinary.com/dbovldjfc/image/upload/v1668718272/farmacia/segurite_zoqte8.jpg",
            description: 'Famosa pastilla para mujeres que cogieron sin proteccion y no quieren hijos porque todas putas',
            stock: 15,
            receta: true,
            day: false,
            isFavorite: false,
        },
        {
            name: 'Simvastatina',
            precio: 10,
            slug: 'simvastatina-888',
            category: 'dolor_de_cabeza',
            image: "https://res.cloudinary.com/dbovldjfc/image/upload/v1668718244/farmacia/simvastatina_lsyjun.jpg",
            description: 'una nueva pastilla para tomar, cada ciertas horas',
            stock: 15,
            receta: true,
            day: true,
            isFavorite: false,
        }, {
            name: 'Amlodipinaa',
            precio: 10,
            slug: 'amlodipina-433',
            category: 'dolor_de_cabeza',
            image: "https://res.cloudinary.com/dbovldjfc/image/upload/v1668718246/farmacia/amlodipina_kt1mie.jpg",
            description: 'una nueva pastilla para tomar, cada ciertas horas',
            stock: 15,
            receta: true,
            day: false,
            isFavorite: false,
        }, {
            name: 'Paracetamol',
            precio: 10,
            slug: 'paracetamol-100',
            category: 'dolor_de_cabeza',
            image: "https://res.cloudinary.com/dbovldjfc/image/upload/v1668718247/farmacia/paracetamol_pt7pwy.webp",
            description: 'una nueva pastilla para tomar, cada ciertas horas',
            stock: 15,
            receta: true,
            day: false,
            isFavorite: false,
        },
        {
            name: 'KevinFake',
            precio: 10,
            slug: 'KevinFake-400',
            category: 'dolor_de_cabeza',
            image: "https://www.casasco.com.ar/wp-content/uploads/2015/09/Pack_web-35_condu500-1.jpg",
            description: 'una nueva pastilla para tomar, cada ciertas horas',
            stock: 15,
            receta: true,
            day: false,
            isFavorite: false,
        },
        {
            name: 'Ultra',
            precio: 10,
            slug: 'ultra-10',
            category: 'dolor_de_cabeza',
            image: "https://res.cloudinary.com/dbovldjfc/image/upload/v1668718246/farmacia/ultra_emhoxo.jpg",
            description: 'una nueva pastilla para tomar, cada ciertas horas',
            stock: 15,
            receta: true,
            day: false,
            isFavorite: false,
        },
        {
            name: 'Lexotiroxina sódica',
            precio: 10,
            slug: 'lexotiroxina-soica-700',
            category: 'dolor_de_cabeza',
            image: "https://res.cloudinary.com/dbovldjfc/image/upload/v1668718245/farmacia/Lexotirorina_ldbvhn.jpg",
            description: 'una nueva pastilla para tomar, cada ciertas horas',
            stock: 15,
            receta: true,
            day: true,
            isFavorite: false,
        },
        {
            name: 'Strepsils',
            precio: 40,
            slug: 'strepsils-x8',
            category: 'dolor_de_garganta',
            image: "https://res.cloudinary.com/dbovldjfc/image/upload/v1670273527/farmacia/strepsils-intensive-caramelos-x-8-unidades_rynofx.png",
            description: 'Se utiliza para el alivio local sintomático de las infecciones leves de boca y garganta que cursan sin fiebre en adultos y niños a partir de 6 años de edad.',
            stock: 15,
            receta: false,
            day: true,
            isFavorite: false,
        },
        {
            name: 'Lizipaina',
            precio: 28,
            slug: 'lizipaina-x20',
            category: 'dolor_de_garganta',
            image: "https://res.cloudinary.com/dbovldjfc/image/upload/v1670273530/farmacia/Lizipaina-20-Comprimidos_g9snr3.jpg",
            description: 'Lizipaína comprimidos se trata de un medicamento de acción calmante y anestésica local que alivia los síntomas y molestias ocasionados debido a la garganta irritada.',
            stock: 15,
            receta: true,
            day: false,
            isFavorite: false,
        },
        {
            name: 'Noraver',
            precio: 45,
            slug: 'noraver-10mg',
            category: 'dolor_de_garganta',
            image: "https://res.cloudinary.com/dbovldjfc/image/upload/v1670273532/farmacia/noraver_gy8lr5.jpg",
            description: 'Noraver Solución Garganta está indicado en los procesos asociados a infecciones localizadas leves, como las úlceras tipo aftas, gingivitis aguda y crónica y dolor en infecciones leves de la garganta como la faringitis aguda.',
            stock: 15,
            receta: false,
            day: true,
            isFavorite: false,
        },

    ],
    category: [
        {
            //id: 1,    //id add auto into db
            value: 'dolor_de_cabeza',
            label: 'dolor de cabeza',
        },
        {
            //id: 2,
            value: 'dolor_de_panza',
            label: 'dolor de panza',
        },
        {
            //id: 3,
            value: 'dolor_de_garganta',
            label: 'dolor de garganta',
        },
    ]
};

export default data;